version: "3.7"
services:

  web1:
    image: web1:1.0
    ports:
      - "8080:80"

  web2productionchoice:
    image: web2productionchoice:1.0
    ports:
      - "8070:80"

  test:
    image: test:1.0