FROM mcr.microsoft.com/dotnet/core/sdk:2.2 as build-env
WORKDIR /web

COPY Shop.Web/*.csproj .
COPY Shop.Lib/*.csproj .

RUN dotnet restore Shop.Web.csproj
RUN dotnet restore Shop.Lib.csproj

COPY Shop.Web/. .
COPY Shop.Lib/. .

RUN dotnet publish Shop.Web.csproj -o publish
WORKDIR /publish
ENTRYPOINT [ "dotnet"]
CMD ["/web/publish/Shop.Web.dll"]